// megafunction wizard: %LPM_DIVIDE%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: LPM_DIVIDE

// ============================================================
// File Name: D:/study/jichuangsai/submit/CICC1002993.srcs/sources_1/ip/hist_divide/hist_divide.v
// Megafunction Name(s):
// 			LPM_DIVIDE
//
// Simulation Library Files(s):
// 			lpm
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// ************************************************************

//Copyright (C) 2017-2020 eHiWay Corporation
//Your use of eHiWay Corporation's design tools, logic functions
//and other software and tools, and its AMPP partner logic
//functions, and any output files from any of the foregoing
//(including device programming or simulation files), and any
//associated documentation or information are expressly subject
//to the terms and conditions of the eHiWay Program License
//Subscription Agreement, eHiWay MegaCore Function License
//Agreement, or other applicable license agreement, including,
//without limitation, that your use is for the sole purpose of
//programming logic devices manufactured by eHiWay and sold by
//eHiWay or its authorized distributors.  Please refer to the
//applicable agreement for further details.


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module  hist_divide (
	clock,
	denom,
	numer,
	quotient,
	remain);

	input	clock;
	input	[20:0]  denom;
	input	[25:0]  numer;
	output	[25:0]  quotient;
	output	[20:0]  remain;

	wire [20:0] sub_wire0;
	wire [25:0] sub_wire1;
	wire [20:0] remain = sub_wire0[20:0];
	wire [25:0] quotient = sub_wire1[25:0];

	lpm_divide	LPM_DIVIDE_component (
				.aclr (1'b0),
				.clock (clock),
				.clken (1'b1),
				.denom (denom),
				.numer (numer),
				.remain (sub_wire0),
				.quotient (sub_wire1));
	defparam
		LPM_DIVIDE_component.lpm_drepresentation = "UNSIGNED",
		LPM_DIVIDE_component.lpm_hint = "LPM_REMAINDERPOSITIVE=TRUE",
		LPM_DIVIDE_component.lpm_nrepresentation = "UNSIGNED",
		LPM_DIVIDE_component.lpm_pipeline = 20,
		LPM_DIVIDE_component.lpm_type = "LPM_DIVIDE",
		LPM_DIVIDE_component.lpm_widthd = 21,
		LPM_DIVIDE_component.lpm_widthn = 26;
endmodule
